ALTER TABLE `nota_credito`
  MODIFY `estado` ENUM('PENDIENTE','PROCESADO','PENDIENTE_REINTENTO','FALLIDO','PENDIENTE_REVISION_MANUAL') NOT NULL DEFAULT 'PENDIENTE',
  ADD COLUMN `motivo` ENUM('RECHAZO_COMERCIO','CANCELACION_CLIENTE','ANULACION_COMERCIO','SUSPENSION_COMERCIO','EXPIRACION_SIN_RESPUESTA') NULL AFTER `monto`,
  ADD COLUMN `mp_payment_id` VARCHAR(50) NULL AFTER `refund_id_mp`,
  ADD COLUMN `ultimo_error` VARCHAR(500) NULL AFTER `mp_payment_id`;
