CREATE TABLE `invitacion_empleado` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `comercio_id` int(11) NOT NULL,
  `email` varchar(254) NOT NULL,
  `codigo` char(6) NOT NULL,
  `estado` enum('PENDIENTE','ACEPTADA','CANCELADA','REEMPLAZADA','VENCIDA','INVALIDADA') NOT NULL DEFAULT 'PENDIENTE',
  `intentos_fallidos` int(11) NOT NULL DEFAULT 0,
  `invitado_por_usuario_id` int(11) NOT NULL,
  `usuario_aceptante_id` int(11) DEFAULT NULL,
  `fecha_creacion` datetime NOT NULL DEFAULT current_timestamp(),
  `fecha_vencimiento` datetime NOT NULL,
  `fecha_resolucion` datetime DEFAULT NULL,
  `pendiente_clave` tinyint(1) GENERATED ALWAYS AS (CASE WHEN `estado` = 'PENDIENTE' THEN 1 ELSE NULL END) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_inv_pendiente_comercio_email` (`comercio_id`,`email`,`pendiente_clave`),
  UNIQUE KEY `uq_inv_pendiente_email_codigo` (`email`,`codigo`,`pendiente_clave`),
  KEY `idx_inv_comercio_fecha` (`comercio_id`,`fecha_creacion`),
  KEY `idx_inv_email_estado` (`email`,`estado`),
  KEY `idx_inv_invitado_por` (`invitado_por_usuario_id`),
  KEY `idx_inv_aceptante` (`usuario_aceptante_id`),
  CONSTRAINT `fk_inv_comercio` FOREIGN KEY (`comercio_id`) REFERENCES `comercio` (`id`),
  CONSTRAINT `fk_inv_invitado_por` FOREIGN KEY (`invitado_por_usuario_id`) REFERENCES `usuario` (`id`),
  CONSTRAINT `fk_inv_aceptante` FOREIGN KEY (`usuario_aceptante_id`) REFERENCES `usuario` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
