SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE detalle_pedido_extra;
TRUNCATE TABLE item_carrito_extra;
TRUNCATE TABLE historial_estado_pedido;
TRUNCATE TABLE reclamo;
TRUNCATE TABLE soporte;
TRUNCATE TABLE detalle_pedido;
TRUNCATE TABLE nota_credito;
TRUNCATE TABLE pago;
TRUNCATE TABLE notificacion;
TRUNCATE TABLE token;
TRUNCATE TABLE sesion;
TRUNCATE TABLE historial_estado_usuario;
TRUNCATE TABLE item_carrito;
TRUNCATE TABLE carrito;
TRUNCATE TABLE imagen_producto;
TRUNCATE TABLE producto_tag;
TRUNCATE TABLE producto_grupo_extra;
TRUNCATE TABLE producto;
TRUNCATE TABLE extra;
TRUNCATE TABLE grupo_extra;
TRUNCATE TABLE horario;
TRUNCATE TABLE red_social;
TRUNCATE TABLE direccion;
TRUNCATE TABLE pedido;
TRUNCATE TABLE empleado_comercio;
TRUNCATE TABLE cuenta_mercado_pago;
TRUNCATE TABLE configuracion_tarifa;
TRUNCATE TABLE historial_estado_comercio;
TRUNCATE TABLE comercio;
TRUNCATE TABLE empleado;
TRUNCATE TABLE dueno;
TRUNCATE TABLE cliente;
TRUNCATE TABLE persona_juridica;
DELETE FROM persona_fisica WHERE id <> 1;
DELETE FROM persona WHERE id <> 1;
DELETE FROM usuario WHERE id <> 1;
SET FOREIGN_KEY_CHECKS=1;
